def createMadLibsStory():
    adjective1 = input("Enter an adjective: ")
    verb = input("Enter a verb: ")
    adjective2 = input("Enter an adjective: ")
    noun = input("Enter a noun: ")
    adjective3 = input("Enter an adjective: ")
    print(f"Today I went to a {adjective1} zoo.")
    print(f"In an exhibit, I saw a {noun}.")
    print(f"The {noun} was {adjective2} and {verb}ing.")
    print(f"I was {adjective3}.")
